### ISSUE TITLE
Handle extra parameters

### ISSUE THREAD

**Issue by Mirch** [soupdevsolutions/pont#7]
The `build` command should be able to take in extra parameters that match placeholders in the `pont.yaml` file. When running the `build` command, these the placeholders should be replaced before running the commands. 

Example: 
```bash
pont build --name foo --from https://github.com/foo/bar baz=fred
```

```yaml
version: 0.2.0
name: foo 
commands:
  - echo "{{baz}}"
```

The output of running the `build command` in this case should be:
```bash
fred
```
